language: python
dist: trusty
python: 3.6.3
services:
    - docker
before_install:
  - sudo apt-get update
  - sudo docker build . -t vision
install:
  - sudo apt-get install python3-pip
  - pip install flake8
script:
  - flake8 --statistics --show-source --disable-noqa
